# Generated by Django 5.2.1 on 2025-06-02 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cursos_carga_horaria_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.AlterModelOptions(
            name='diciplinacurso',
            options={'verbose_name': 'Disciplina do curso', 'verbose_name_plural': 'Disciplinas do curso'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='periodocurso',
            options={'verbose_name': 'Período do curso', 'verbose_name_plural': 'Períodos do curso'},
        ),
        migrations.AlterModelOptions(
            name='tipoavaliacao',
            options={'verbose_name': 'Tipo de avaliação', 'verbose_name_plural': 'Tipos de avaliação'},
        ),
        migrations.AlterField(
            model_name='avaliacoes',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='avaliacoes',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='carga_horaria_total',
            field=models.CharField(max_length=4, verbose_name='Carga horária total'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicao', verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='diciplinacurso',
            name='carga_horaria',
            field=models.CharField(max_length=100, verbose_name='Carga horária'),
        ),
        migrations.AlterField(
            model_name='diciplinacurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='diciplinacurso',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periodocurso', verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_prev_termino',
            field=models.DateField(verbose_name='Data previsão término'),
        ),
        migrations.AlterField(
            model_name='ocorrencias',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='ocorrencias',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='periodocurso',
            name='numero',
            field=models.IntegerField(verbose_name='Número período'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='ocupacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ocupacao', verbose_name='Ocupação'),
        ),
        migrations.AlterField(
            model_name='tipoavaliacao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Tipo de avaliação'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='periodo',
            field=models.CharField(max_length=100, verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='turmas',
            name='turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.turno', verbose_name='Turno'),
        ),
    ]
